# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

stages:
- stage: Terraform
  displayName: 'Terraform Deployment'
  jobs:
  - job: TerraformApply
    displayName: 'Apply Terraform for ADBS'
    pool:
      name: Default

    steps:
    # Terraform + Azure CLI combined
    - task: AzureCLI@2
      displayName: 'Terraform Init/Plan/Apply on Azure'
      inputs:
        azureSubscription: '$(AZURE_SERVICE_CONNECTION_NAME)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Terraform + Azure CLI auth starting..."
             
          # Terraform Init
          terraform init
          
          # Terraform Plan
          terraform plan -var-file="dev.tfvars" -out=tfplan
          
          # Terraform Apply
          terraform apply -auto-approve tfplan